### ISSUE TITLE
Error: Unable to resolve module `./src/DarkMoodSwitch` from `node_modules\react-native-animated-switch\index.js`:

### ISSUE THREAD

**Issue by vuongnh1705** [vijaydemonz/react-native-animated-switch-npm#1]

**Comment by andreivasilescu1995** [comment]
Any fixes?

**Comment by vijaydemonz** [comment]
Please check the latest version. Reopen if Problem Still exists.Thanks

**Comment by EndLess728** [comment]
I just installed the library and faced this issue is still there, Also I faced issue with spring switcher for spring switcher activecolor and inactive color is reveresed.
